GET http://localhost:3000/users/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiZmVsb0BnbWFpbC5jb20iLCJpYXQiOjE2ODY4NTE1MDIsImV4cCI6MTY4Njg1MjQwMn0.U-o0tQ9A405_Mav2ijg0y5oqbu5VET4eC2Xuau5kUzA
